### ISSUE TITLE
Archive of version 1.0.40 is not available at http://download.ros.org/downloads/rospkg/

### ISSUE THREAD

**Issue by bulwahn** [ros-infrastructure/rospkg#107]
The PyPI page [1] points to http://download.ros.org/downloads/rospkg/ for downloading the rospkg python package, but unfortunately, the archive of the latest version 1.0.40 is not available there. Maybe this step was forgotten/broke in the release process of this package?

[1] https://pypi.python.org/pypi/rospkg/1.0.40

**Comment by dirk-thomas** [comment]
@wjwwood it looks like you released the latest version (cf4dba5c6d1ce85bbbb88f2dfa7e9d5c65382eb3). Can you please upload the missing archive.

**Comment by tfoote** [comment]
It's odd that this failed for both @wjwwood's and my uploads recently https://github.com/vcstools/vcstools/issues/121 we'll have to make sure that if it fails to push that it is more obvious. 

I've pushed the tarball for rospkg too.

**Comment by wjwwood** [comment]
Thanks @tfoote, I'll keep an eye out for the failure in future releases.
