### ISSUE TITLE
Fix detection for derivative (rebranded) OS

### ISSUE THREAD

**Issue by breznak** [ros-infrastructure/rospkg#108]
for example Neon (Ubuntu), ...

As per specification, the `os-release` has `ID` and `ID_LIKE` fields.

Proposal:
Parse the `ID_LIKE` if the first try fails.

Reported in: ros/rosdistro#12716

**Comment by breznak** [comment]
> and rosdep will need to be extended to show that Neon is an alias to Ubuntu. 

@tfoote would this be necessary for `rosdep`? I think it would be more future-proof to try to install with ID, if that fails then fallback to ID_LIKE OS-names. (So it tries to install Neon, fails, and installs as Ubuntu)

**Comment by orzechow** [comment]
@tfoote Thanks for that, I'd love to see this released in v1.0.41 soon!

**Comment by tfoote** [comment]
@orzechow We're in the middle of a large rebuild of kinetic and are preparing for ROSCon I don't think we're going to have time for this release immediately. If you need it soon. You can relatively quickly install it from source.

**Comment by dirk-thomas** [comment]
I just released 1.0.41. I will be in the apt repos shortly.

**Comment by orzechow** [comment]
Thanks a lot!
