### ISSUE TITLE
roslaunch does not work when same package is in both src and install space

### ISSUE THREAD

**Issue by sachinchitta** [ros-infrastructure/rospkg#11]
Follow the moveit installation instructions on http://moveit.ros.org/installation_source.html

and then try:

roslaunch pr2_moveit_config demo.launch

Error:

multiple files named [demo.launch] in package [pr2_moveit_config]:
- /opt/ros/groovy/share/pr2_moveit_config/launch/demo.launch
- /wg/stor2a/sachinc/code-new/prx_alpha_groovy/src/moveit_pr2/pr2_moveit_config/launch/demo.launch
  Please specify full path instead

**Comment by rubenalvesbcn** [comment]
Was this solved?
