### ISSUE TITLE
OsDetect gives wrong codename on debian:buster

### ISSUE THREAD

**Issue by weichm** [ros-infrastructure/rospkg#125]
```
>>> import platform
>>> platform.linux_distribution()
('debian', 'buster/sid', '')
```
The last field should not be empty, as it is used for example in `ros-dep`, causing problems on debian:buster (see https://github.com/ros/rosdistro/issues/16768#issuecomment-361711437).

The last field should be `'buster'`.

**Cause of the error:**

The codename in the debian case is calculated from the version (https://github.com/ros-infrastructure/rospkg/blob/master/src/rospkg/os_detect.py#L149):

```
>>> from rospkg import os_detect
>>> lsb = os_detect.LsbDetect('debian')
>>> lsb.get_codename()
''
>>> lsb.get_version()
'buster/sid'
```

**Comment by mikaelarguedas** [comment]
```
>>> import platform
>>> platform.linux_distribution()
('debian', 'buster/sid', '')
```
Actually I think it's fine that the field is empty. As pointed in your link, rosdep relies on the [version number](https://github.com/ros-infrastructure/rospkg/blob/4dd94ec551a6080e4fb6d7f81bbab7ede774d26f/src/rospkg/os_detect.py#L161) to infer the codename. `buster` currently is labeled as `testing` and doesnt have an assigned major version number. 
While we could update rospkg to map "testing" to "buster" this would break as soon as debian gives it a proper version number which IMO is not desired.
As long as debian doesnt provide a version number for buster, I think it's fine to have to pass the OS explicitly to rosdep (as I would understand if the rospkg maintainers are not willing to change the logic of how the codenames are detected for the specific usecase of "unstable" versions).

**Comment by tfoote** [comment]
Yeah, until buster's identification gets finalized I'd suggest that we use the key `buster` and recommend using the override arguments. In the mean time we could add version '10.' speculatively to the code to be ready when buster gets more clearly declared.

**Comment by dirk-thomas** [comment]
What is the status of this ticket? If we want to add handling of version 10 to the logic can someone create a PR for that?

**Comment by mikaelarguedas** [comment]
PR here: https://github.com/ros-infrastructure/rospkg/pull/135

**Comment by mikaelarguedas** [comment]
I think that once #135 merged, this issue is addressed and can be closed (even though not fixed as user still have to explicitly specify the OS).
