### ISSUE TITLE
[get_depends] ResourceNotFound exception occurs when "build_depend"-ed pkgs not found

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/rospkg#131]
Please correct me if I'm wrong, but it's legally possible that some packages don't get installed when you strictly install the packages only in dependency chain (e.g. using `rosdep install --from-paths src --ignore-src -r -y`). I've found those that are only `build_depend`-ed in the dependency chain might not get installed? (, an example of which in my case is `roslang`) I'm not sure exactly why, but I found it not installed on my environment (and it makes sense to me. <s>I guess this is related to why we needed version 3 of package.xml format</s>).

Then, `RosPack.get_depends` [traverses all `*_depend`](https://github.com/ros-infrastructure/rospkg/blob/8bfc04ae7062f7e4e4046f0175f60d2930f37f7a/src/rospkg/manifest.py#L419) existing in the `package.xml` format. This results in `ResourceNotFound` exception on the environment like I described above.

This is not intuitive so needs to be fixed IMO, but I'm not sure what's the best solution. Do we want to search only `run_depend` by default and add an option to search all `*_depend`s?
If someone guides the direction I might be able to create a patch.

```
$ apt-cache policy python-rospkg
python-rospkg:
  Installed: 1.1.4-100
  Candidate: 1.1.4-100
  Version table:
 *** 1.1.4-100 500
        500 http://packages.ros.org/ros/ubuntu xenial/main amd64 Packages
        500 http://packages.ros.org/ros/ubuntu xenial/main i386 Packages
        100 /var/lib/dpkg/status
     1.0.38-1 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe i386 Packages
$ env|grep -i pythonpath
PYTHONPATH=/opt/ros/kinetic/lib/python2.7/dist-packages
$ apt-cache policy ros-kinetic-roslang                                                                                     
ros-kinetic-roslang:
  Installed: (none)
  Candidate: 1.13.6-0xenial-20171104-174440-0800
  Version table:
     1.13.6-0xenial-20171104-174440-0800 500
        500 http://packages.ros.org/ros/ubuntu xenial/main amd64 Packages
$ ipython
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
Type "copyright", "credits" or "license" for more information.

IPython 2.4.1 -- An enhanced Interactive Python.

In [1]: from rospkg import RosPack
In [2]: rp = RosPack()
In [4]: rp.get_depends('roscpp')                                                                                                                                                                            
---------------------------------------------------------------------------
ResourceNotFound                          Traceback (most recent call last)
<ipython-input-4-e26b635a40aa> in <module>()
----> 1 rp.get_depends('roscpp')

/usr/lib/python2.7/dist-packages/rospkg/rospack.pyc in get_depends(self, name, implicit)
    238 
    239             for p in names:
--> 240                 s.update(self.get_depends(p, implicit))
    241             # add in our own deps
    242             s.update(names)

/usr/lib/python2.7/dist-packages/rospkg/rospack.pyc in get_depends(self, name, implicit)
    232 
    233             # take the union of all dependencies
--> 234             names = [p.name for p in self.get_manifest(name).depends]
    235 
    236             # assign key before recursive call to prevent infinite case

/usr/lib/python2.7/dist-packages/rospkg/rospack.pyc in get_manifest(self, name)
    165             return self._manifests[name]
    166         else:
--> 167             return self._load_manifest(name)
    168 
    169     def _update_location_cache(self):

/usr/lib/python2.7/dist-packages/rospkg/rospack.pyc in _load_manifest(self, name)
    209         :raises: :exc:`ResourceNotFound`
    210         """
--> 211         retval = self._manifests[name] = parse_manifest_file(self.get_path(name), self._manifest_name, rospack=self)
    212         return retval
    213 

/usr/lib/python2.7/dist-packages/rospkg/rospack.pyc in get_path(self, name)
    201         self._update_location_cache()
    202         if name not in self._location_cache:
--> 203             raise ResourceNotFound(name, ros_paths=self._ros_paths)
    204         else:
    205             return self._location_cache[name]

ResourceNotFound: roslang
ROS path [0]=/opt/ros/kinetic/share/ros
ROS path [1]=/opt/ros/kinetic/share
```

**Comment by dirk-thomas** [comment]
If you install the Debian package of  a ROS package that will only require the run dependencies of that ROS package to be installed - simply because the package has already been built and therefore its build dependencies are not necessary.

**Comment by dirk-thomas** [comment]
> I guess this is related to why we needed version 3 of package.xml format

I don't see how this would be related to version 3 of the package manifest format?

**Comment by dirk-thomas** [comment]
Has my previous comment answered your question? Should this ticket be closed or can you clarify what the goal of the issue is?

**Comment by 130s** [comment]
>>     I guess this is related to why we needed version 3 of package.xml format
>
> I don't see how this would be related to version 3 of the package manifest format?

I think I was wrong. Yes, nothing related.

> If you install the Debian package of a ROS package that will only require the run dependencies of that ROS package to be installed - simply because the package has already been built and therefore its build dependencies are not necessary.

Thanks for the confirmation.
Based on that, I opened https://github.com/ros-infrastructure/rospkg/pull/132 to make `get_depends` return less confusing result.
