### ISSUE TITLE
Simplify AplineOS codename (remove patch version)

### ISSUE THREAD

**Issue by MarkHedleyJones** [ros-infrastructure/rospkg#177]
In order to release ROS on Alpine Linux in future, it will be necessary to specify the Alpine versions in the relevant distribution file (e.g. [rosdistro/melodic/distribution.yaml](https://github.com/ros/rosdistro/blob/master/melodic/distribution.yaml)). Currently, Alpine's OS codename is formatted according to the semantic versioning system MAJOR.MINOR.PATCH. This means that it is also necessary to specify Alpine versions using this format inside distribution.yaml files. However, it seems unnecessary to match against the operating system's patch version.

An example of how we're dealing with the Alpine formatted release name names can be found [here](https://github.com/seqsense/aports-ros-experimental/blob/master/backports/py-rosdistro/force-to-enable-alpine-platform.patch)
In that instance, we are required to specify patch level versions like:
```
       if name == 'kinetic':
           self.release_platforms['alpine'].append('3.7.0')
           self.release_platforms['alpine'].append('3.7.1')
           self.release_platforms['alpine'].append('3.7.2')
           self.release_platforms['alpine'].append('3.7.3')
```
But, it is desirable to specify the version like so:
```
       if name == 'kinetic':
           self.release_platforms['alpine'].append('3.7')
```
While the example is just a patch, in future we hope that Alpine will be fully support by ROS, and therefore wish to avoid the overly verbose requirement of specifying patch level versions.

**Comment by dirk-thomas** [comment]
@MarkHedleyJones Please consider to contribute a pull request for this.

**Comment by MarkHedleyJones** [comment]
@dirk-thomas, after discussion in #178 it was decided to modify only rosdep to achieve this.
Please see https://github.com/ros-infrastructure/rosdep/pull/716

**Comment by dirk-thomas** [comment]
In the future please close the ticket yourself.

**Comment by MarkHedleyJones** [comment]
Sorry :bowing_man:
