### ISSUE TITLE
rosversion does not find meta-packages

### ISSUE THREAD

**Issue by tkruse** [ros-infrastructure/rospkg#18]
$ rosversion ros_comm
Cannot locate [ros_comm]!!!

$ rosversion ros
Cannot locate [ros]!!!

**Comment by 130s** [comment]
Years passed, and I see `package.xml` for a metapackage installed. I'm not sure all of developments over these years though, does it now make sense to reconsider allowing `rosversion <metapkg>` to return a version?

I'm suggesting my team to rely on `rosversion <metapkg>` for version checking then hit this ticket.

```
# ls -l `find /opt/ros/kinetic/ -iname ros_comm`
total 4
-rw-r--r-- 1 root root 2228 Aug 23  2018 package.xml

# apt-cache policy ros-kinetic-ros-comm
ros-kinetic-ros-comm:
  Installed: 1.12.14-0xenial-20200218-163317+0000
```

**Comment by tfoote** [comment]
That seems reasonable to reconsider now if we can valiadate that the package.xml content is available in all cases.
