### ISSUE TITLE
debian package creates python3-shebang in rosversion entrypoint

### ISSUE THREAD

**Issue by timeamagyar** [ros-infrastructure/rospkg#195]
Hi,

I observed for version 1.2.4-100, that `rosversion` would get a hard coded `/usr/bin/python3` shebang on my system, upon installation.
I believe this should be virtualenv enabled and be set to an environment-specific python version, so python2 can be used transparently.
Since I stumbled upon this, while using `roslaunch`, I would also argue that `roslaunch` depending on the `rosversion` entry-point, instead of directly referencing the Python script might be the real issue here.

Once I hard coded to a python2 shebang for the `rosversion` entrypoint, I was able to use `roslaunch` in a python2-environment.
I am not familiar with Ubuntu deb-packaging, so it would be great if someone could look into this.

**Comment by dirk-thomas** [comment]
What exact Debian packages did you install?

**Comment by timeamagyar** [comment]
Hi,
it was the debian package python-rospkg (1.2.4-100).

**Comment by dirk-thomas** [comment]
I just double checked the Debian package (http://packages.ros.org/ros-testing/ubuntu/pool/main/p/python-rospkg/python-rospkg_1.2.4-100_all.deb) and the shebang line of the `/usr/bin/rosversion` and it is `#! /usr/bin/python` as expected.

 So it seems something is different . custom on your system. Please try to reinstall the Debian package and check that the executable has the right shebang line afterward.

**Comment by dirk-thomas** [comment]
I will go ahead and close this ticket since there seems to be nothing wrong with the code of this repo. Please feel free to continue commenting.
