### ISSUE TITLE
Version 1.3.0 is not available for ARM architectures

### ISSUE THREAD

**Issue by deadln** [ros-infrastructure/rospkg#225]
I recently released a [package](https://github.com/ros/rosdistro/pull/29678) for rosdistro. This package succesfully builds for [amd64](https://build.ros.org/view/Mbin_uB64/job/Mbin_uB64__clover__ubuntu_bionic_amd64__binary/3/console) architecture but fails for [arm64](https://build.ros.org/view/Mbin_ubv8_uBv8/job/Mbin_ubv8_uBv8__clover__ubuntu_bionic_arm64__binary/4/console) and [armhf](https://build.ros.org/view/Mbin_ubhf_uBhf/job/Mbin_ubhf_uBhf__clover__ubuntu_bionic_armhf__binary/4/console) with same error
`ERROR: rosdep-modules 0.20.1 has requirement rospkg>=1.3.0, but you'll have rospkg 1.2.6 which is incompatible.`

**Comment by CursedRock17** [comment]
rospkg is now on 1.5 and rosdep installs rospkg on version 1.4 so it's probably safe to say it would work on arm64 at version 1.3, and can probably have this issue closed.
