### ISSUE TITLE
Add support for newer versions of Mint

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rospkg#25]
From ros/rosdep#200 the Mint detector currently has a hard coded table, which is out of date.  An algorithm to make Mint robust to new releases would be better.

**Comment by tfoote** [comment]
The OS detection is done in this module: https://github.com/ros-infrastructure/rospkg/blob/master/src/rospkg/os_detect.py

**Comment by dirk-thomas** [comment]
Closing this due to no further activity.
