### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by jvgomez** [ros-infrastructure/rospkg#83]
Or I am doing something wrong. Following code inspired from the [example in the documentation](http://docs.ros.org/independent/api/rospkg/html/rospkg_packages.html#rospkg.RosPack)

```python
from rospkg import RosPack
rp = RosPack()
pkgs = rp.list_packages()
```

Returns:
```
Traceback (most recent call last):
    ...
 pkgs = rp.list_packages()
AttributeError: 'RosPack' object has no attribute 'list_packages'
```

After digging I saw that now is `rp.list()`.

I also found lots of difficulties to find this repo from the documentation. A link somewhere would be useful (sorry if there is one and I couldn't find it).

**Comment by tfoote** [comment]
Can you point to the documentation that you're referring to?

**Comment by jvgomez** [comment]
I edited the post just before reading your comment :)
It is also here: https://github.com/ros-infrastructure/rospkg/blob/master/src/rospkg/rospack.py#L308

**Comment by dirk-thomas** [comment]
Thanks for the feedback. Fixed in the referenced commit.

**Comment by jvgomez** [comment]
If I knew it was only those changes I would have done it myself hehe. Thanks for the quick fix!
