### ISSUE TITLE
rosdep init breaks with rospkg 1.0.37 for python3

### ISSUE THREAD

**Issue by jjekircp** [ros-infrastructure/rospkg#91]
I noticed a bunch of builds on ros_buildfarm failing all of a sudden when running `rosdep init`, then realized it was only the builds that had updated to rospkg 1.0.37 that were failing. ros_buildfarm uses python3 in many places, particularly the Python packages for catkin, rosdistro, rospkg, rosdep, and similar infrastructure tools.

These are the commands I used to set up a python3 virtualenv with the `rospkg` and `rosdep` packages:

```
$ python3 -m venv --without-pip venv-3.4
$ source venv-3.4/bin/activate
$ curl https://bootstrap.pypa.io/get-pip.py | python3
$ pip3 install rospkg rosdep
$ sudo -i
# cd ~jjekir/tmp/venv-3.4
# source bin/activate
# cd /etc/ros/rosdep/sources.list.d
# rm 20-default.list 
# which rosdep
/home/jjekir/tmp/venv-3.4/bin/rosdep
# pip freeze | grep rospkg
rospkg==1.0.37
# pip freeze | grep rosdep
rosdep==0.11.4
```

I then ran `rosdep init` which yielded the following error (matching what I saw inside ros_buildfarm)
```
(venv-3.4) root@hostname:/etc/ros/rosdep/sources.list.d# rosdep init
Traceback (most recent call last):
  File "/home/jjekir/tmp/venv-3.4/bin/rosdep", line 3, in <module>
    from rosdep2.main import rosdep_main
  File "/home/jjekir/tmp/venv-3.4/lib/python3.4/site-packages/rosdep2/__init__.py", line 40, in <module>
    from .installers import InstallerContext, Installer, \
  File "/home/jjekir/tmp/venv-3.4/lib/python3.4/site-packages/rosdep2/installers.py", line 35, in <module>
    from rospkg.os_detect import OsDetect
  File "/home/jjekir/tmp/venv-3.4/lib/python3.4/site-packages/rospkg/os_detect.py", line 621, in <module>
    OsDetect.register_default(OS_FEDORA, FdoDetect("fedora"))
  File "/home/jjekir/tmp/venv-3.4/lib/python3.4/site-packages/rospkg/os_detect.py", line 153, in __init__
    if release_info is not None and release_info.has_key("ID") and release_info["ID"] == fdo_id:
AttributeError: 'dict' object has no attribute 'has_key'
```

Please let me know if there is any other information that would be necessary or helpful to resolve this issue.

**Comment by tfoote** [comment]
I think this is already fixed in #90 can you confirm?

**Comment by jjekircp** [comment]
Confirmed; I checked out bcef51dc95be9fb3f8b2f85fe34cd06a5c3a79c5 and `rosdep init` completed without error.

**Comment by tfoote** [comment]
closing as duplicate/fixed

**Comment by tfoote** [comment]
Thanks for the confirmation.

**Comment by jjekircp** [comment]
I realize that #90 was very recently merged, but when can we expect an updated package in apt and PyPi?

**Comment by tfoote** [comment]
It's out now on all channels
